### ISSUE TITLE
Observable<any> is not assignable to type QueueingSubject<any>

### ISSUE THREAD

**Issue by emnkoksal** [ohjames/rxjs-websockets#21]
I am talking about this example:

https://www.npmjs.com/package/angular2-websocket-service

**1-** Here the package is angular2-websocket-service but on github it is rxjs-websockets
**2-** In the example share is not defined; missing rxjs/share import
**3-** The second parameter of this.socketFactory.connect requires Observable<any>. QueueingSubject<any> is not accepted. Gives compile error (ng build)
**4-** When I pass an Observable<any> and try to subscribe, gives "property subscribe of undefined not found" error.

**Comment by ohjames** [comment]
1. That is a *different package* that includes my package as a dependency. It is a good idea to minimally educate yourself before raising github tickets.
2. Because you didn't learn how to import rxjs operators or that package is using an old rxjs-websockets package that doesn't require rxjs as a peer dependency.
3. QueueingSubject is an Observable. All subjects are. You can also call toObservable() on them to restrict the interface.
4. Well that's not my package and you didn't include any code?

**Comment by ohjames** [comment]
Gets rxjs-websockets not that ancient package.
